name: Python Tests

on: [pull_request]

jobs:
  build:
    name: Run Tests
    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1

      - name: Install Pylint
        run: pip install pylint

      - name: Lint
        run: pylint octopy

      - name: Run Tests
        run: make test

      - name: Run Executable
        run: ./scripts/testprogram.sh
