name: Python Tests

on: [pull_request]

jobs:
  build:
    name: Run Tests
    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v2
      - name: Run Tests
        run: make test

      - name: Run Executable
        run: ./scripts/testprogram.sh
